### ISSUE TITLE
create initial jhuda-docker

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-docker#1]
The initial set up in jhuda-docker should contain components necessary to Implement the public URIs solution to "The URI Problem" as documented here: https://docs.google.com/document/d/1ynNYuiukEzc-rH-JoIDwXTF02jeYTu_gmZcXRcKHOsA/edit#

Please use your judgement on when this ticket can be closed: somewhere between it can be built successfully and it has enough components.

**Comment by emetsger** [comment]
closed per #2

**Comment by emetsger** [comment]
Oh sorry, re-opening.  #2 does _not_ deal with the URI problem.  Itchy trigger finger here!

**Comment by htpvu** [comment]
@emetsger in reference to section "In jhuda-docker" in the above linked to doc, which portion of the "URI problem" is outstanding?

**Comment by emetsger** [comment]
Closed by #4
